# This is a basic workflow to help you get started with Actions

name: master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SSH:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MASTER_HOST }}
          username: ${{ secrets.USER }}
          port : ${{secrets.PORT}}
          password : ${{secrets.MASTER_PASSWORD}}
          script: 
            cd /var/www/momok &&
            git reset --hard master &&
            git fetch &&
            git pull origin master &&
            npm install &&
            npm run build && 
            pm2 reload 0
